<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: DejaVu Sans, sans-serif; font-size: 8px; color: #111; }
  .header { background: #1a56db; color: white; padding: 10px 14px; margin-bottom: 8px; }
  .header h1 { font-size: 14px; margin-bottom: 2px; }
  .header p { font-size: 9px; opacity: 0.85; }
  .meta { display: flex; justify-content: space-between; padding: 4px 0 8px; font-size: 9px; color: #374151; }
  .meta strong { color: #111; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #374151; color: white; padding: 4px 3px; text-align: left; font-size: 7.5px; }
  td { padding: 3px; border-bottom: 1px solid #e5e7eb; font-size: 7.5px; }
  tr:nth-child(even) td { background: #f9fafb; }
  .total-row td { background: #f0fdf4 !important; font-weight: bold; border-top: 2px solid #16a34a; }
  .text-right { text-align: right; }
  .footer { margin-top: 10px; font-size: 8px; color: #6b7280; text-align: center; }
</style>
</head>
<body>

<div class="header">
  <h1>LEO GROUP — BILL STATEMENT</h1>
  <p>Pharmaceutical Distribution</p>
</div>

<div class="meta">
  <div><strong>Bill No:</strong> {{ $billNo }}</div>
  <div><strong>Customer:</strong> {{ $customerName }}</div>
  <div><strong>Date:</strong> {{ $billDate }}</div>
  <div><strong>Net Amount:</strong> ₹{{ number_format($netAmount, 2) }}</div>
</div>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Item Name</th>
      <th>Company</th>
      <th>Batch</th>
      <th>Expiry</th>
      <th class="text-right">Qty</th>
      <th class="text-right">Free</th>
      <th class="text-right">Rate</th>
      <th class="text-right">MRP</th>
      <th class="text-right">Disc%</th>
      <th class="text-right">Taxable</th>
      <th class="text-right">GST%</th>
      <th class="text-right">GST Val</th>
      <th class="text-right">Total</th>
      <th>HSN</th>
    </tr>
  </thead>
  <tbody>
    @foreach($items as $i => $item)
    <tr>
      <td>{{ $i + 1 }}</td>
      <td>{{ $item['ITEMNAME'] ?? '' }}</td>
      <td>{{ $item['COMPNAME'] ?? '' }}</td>
      <td>{{ $item['BATCHNO'] ?? '' }}</td>
      <td>{{ $item['EXPIRYDATE'] ?? '' }}</td>
      <td class="text-right">{{ $item['QUANTITY'] ?? 0 }}</td>
      <td class="text-right">{{ $item['FREE'] ?? 0 }}</td>
      <td class="text-right">{{ number_format($item['SRATE'] ?? 0, 2) }}</td>
      <td class="text-right">{{ number_format($item['PMRP'] ?? 0, 2) }}</td>
      <td class="text-right">{{ $item['DISCOUNT'] ?? 0 }}</td>
      <td class="text-right">{{ number_format($item['TAXABLE'] ?? 0, 2) }}</td>
      <td class="text-right">{{ $item['GSTRATE'] ?? 0 }}%</td>
      <td class="text-right">{{ number_format($item['GSTVALUE'] ?? 0, 2) }}</td>
      <td class="text-right"><strong>{{ number_format($item['TOTALAMOUNT'] ?? 0, 2) }}</strong></td>
      <td>{{ $item['HSNCODE'] ?? '' }}</td>
    </tr>
    @endforeach
    <tr class="total-row">
      <td colspan="13" class="text-right">NET AMOUNT:</td>
      <td class="text-right">₹{{ number_format($netAmount, 2) }}</td>
      <td></td>
    </tr>
  </tbody>
</table>

<div class="footer">
  Generated by LEO Group Bill Management System · {{ now()->format('d M Y, h:i A') }}
</div>

</body>
</html>
